/**
 * A2UI React Native Example App
 *
 * Demonstrates the A2UI renderer with a static spec.
 * For streaming examples, see StreamingApp.tsx
 */

import React, { useState } from 'react';
import { SafeAreaView, StyleSheet, Text, View, ScrollView } from 'react-native';
import { A2UIRenderer, ActionPayload } from '../src';

// Example A2UI spec - simulating what an agent would send
const exampleSpec = {
  surfaceId: 'main',
  rootId: 'root',
  components: [
    // Root column layout
    {
      id: 'root',
      type: 'Column' as const,
      children: ['header', 'content-card', 'actions-row'],
      style: { padding: 16 },
    },

    // Header text
    {
      id: 'header',
      type: 'Text' as const,
      content: 'Welcome to A2UI',
      textStyle: {
        fontSize: 24,
        fontWeight: 'bold' as const,
        color: '#1a1a1a',
        textAlign: 'center' as const,
      },
    },

    // Content card with info
    {
      id: 'content-card',
      type: 'Card' as const,
      children: ['card-title', 'card-body', 'list-demo'],
    },

    {
      id: 'card-title',
      type: 'Text' as const,
      content: 'Agent Response',
      textStyle: {
        fontSize: 18,
        fontWeight: '600' as const,
        color: '#333',
      },
    },

    {
      id: 'card-body',
      type: 'Text' as const,
      content: 'This UI was generated by an AI agent using the A2UI protocol. The components below demonstrate different UI capabilities.',
    },

    // List demonstration
    {
      id: 'list-demo',
      type: 'Column' as const,
      children: ['list-header', 'item1', 'item2', 'item3'],
      style: { marginTop: 12 },
    },

    {
      id: 'list-header',
      type: 'Text' as const,
      content: 'Features:',
      textStyle: { fontWeight: '600' as const, marginBottom: 8 },
    },

    {
      id: 'item1',
      type: 'Row' as const,
      children: ['item1-bullet', 'item1-text'],
      style: { alignItems: 'center', marginVertical: 4 },
    },
    { id: 'item1-bullet', type: 'Text' as const, content: '•  ' },
    { id: 'item1-text', type: 'Text' as const, content: 'Declarative UI generation' },

    {
      id: 'item2',
      type: 'Row' as const,
      children: ['item2-bullet', 'item2-text'],
      style: { alignItems: 'center', marginVertical: 4 },
    },
    { id: 'item2-bullet', type: 'Text' as const, content: '•  ' },
    { id: 'item2-text', type: 'Text' as const, content: 'Real-time streaming updates' },

    {
      id: 'item3',
      type: 'Row' as const,
      children: ['item3-bullet', 'item3-text'],
      style: { alignItems: 'center', marginVertical: 4 },
    },
    { id: 'item3-bullet', type: 'Text' as const, content: '•  ' },
    { id: 'item3-text', type: 'Text' as const, content: 'Data binding support' },

    // Actions row with buttons
    {
      id: 'actions-row',
      type: 'Row' as const,
      children: ['primary-btn', 'secondary-btn'],
      style: { justifyContent: 'space-around', marginTop: 16 },
    },

    {
      id: 'primary-btn',
      type: 'Button' as const,
      label: 'Learn More',
      action: 'learn_more',
      variant: 'primary' as const,
    },

    {
      id: 'secondary-btn',
      type: 'Button' as const,
      label: 'Dismiss',
      action: 'dismiss',
      variant: 'secondary' as const,
    },
  ],
  dataModel: {},
};

export default function App() {
  const [lastAction, setLastAction] = useState<ActionPayload | null>(null);

  const handleAction = (payload: ActionPayload) => {
    console.log('Action received:', payload);
    setLastAction(payload);
  };

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView contentContainerStyle={styles.scrollContent}>
        {/* Render the A2UI spec */}
        <A2UIRenderer spec={exampleSpec} onAction={handleAction} />

        {/* Show last action for debugging */}
        {lastAction && (
          <View style={styles.debugContainer}>
            <Text style={styles.debugTitle}>Last Action:</Text>
            <Text style={styles.debugText}>
              {JSON.stringify(lastAction, null, 2)}
            </Text>
          </View>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  scrollContent: {
    padding: 16,
  },
  debugContainer: {
    marginTop: 24,
    padding: 12,
    backgroundColor: '#fff3cd',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ffc107',
  },
  debugTitle: {
    fontWeight: '600',
    marginBottom: 8,
    color: '#856404',
  },
  debugText: {
    fontFamily: 'monospace',
    fontSize: 12,
    color: '#856404',
  },
});
