#!/bin/bash
# A2UI API Test Script
# Run: chmod +x test-a2ui.sh && ./test-a2ui.sh

BASE_URL="http://localhost:3000"
SURFACE_ID="test-surface-$(date +%s)"
SESSION_ID="session-123"
CATALOG_ID="https://a2ui.dev/specification/0.9/standard_catalog_definition.json"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "🧪 Testing A2UI API"
echo "==================="
echo ""

# 1. Create Surface
echo "1️⃣  Creating surface: $SURFACE_ID"
curl -s -X POST "$BASE_URL/a2ui/surfaces?sessionId=$SESSION_ID" \
  -H "Content-Type: application/json" \
  -d "{
    \"surfaceId\": \"$SURFACE_ID\",
    \"catalogId\": \"$CATALOG_ID\"
  }" | jq .
echo ""

# 2. List Surfaces
echo "2️⃣  Listing all surfaces"
curl -s "$BASE_URL/a2ui/surfaces?sessionId=$SESSION_ID" | jq .
echo ""

# 3. Get Surface
echo "3️⃣  Getting surface: $SURFACE_ID"
curl -s "$BASE_URL/a2ui/surfaces/$SURFACE_ID?sessionId=$SESSION_ID" | jq .
echo ""

# 4. Update Components
echo "4️⃣  Updating components"
curl -s -X PUT "$BASE_URL/a2ui/surfaces/$SURFACE_ID/components?sessionId=$SESSION_ID" \
  -H "Content-Type: application/json" \
  -d "{
    \"components\": [
      {
        \"id\": \"welcome-text\",
        \"component\": \"Text\",
        \"text\": \"Welcome to A2UI!\",
        \"usageHint\": \"h1\"
      },
      {
        \"id\": \"description\",
        \"component\": \"Text\",
        \"text\": \"This is a dynamic UI generated by an AI agent.\",
        \"usageHint\": \"body\"
      },
      {
        \"id\": \"main-column\",
        \"component\": \"Column\",
        \"children\": [\"welcome-text\", \"description\"],
        \"alignment\": \"center\"
      }
    ]
  }" | jq .
echo ""

# 5. Get Updated Surface
echo "5️⃣  Getting updated surface"
curl -s "$BASE_URL/a2ui/surfaces/$SURFACE_ID?sessionId=$SESSION_ID" | jq .
echo ""

# 6. Update Data Model
echo "6️⃣  Updating data model"
curl -s -X PUT "$BASE_URL/a2ui/surfaces/$SURFACE_ID/data?sessionId=$SESSION_ID" \
  -H "Content-Type: application/json" \
  -d "{
    \"path\": \"/user\",
    \"op\": \"add\",
    \"value\": {
      \"name\": \"Test User\",
      \"email\": \"test@example.com\"
    }
  }" | jq .
echo ""

# 7. Send User Action
echo "7️⃣  Sending user action (triggers event flow)"
curl -s -X POST "$BASE_URL/a2ui/actions" \
  -H "Content-Type: application/json" \
  -d "{
    \"surfaceId\": \"$SURFACE_ID\",
    \"sessionId\": \"$SESSION_ID\",
    \"name\": \"button_click\",
    \"sourceComponentId\": \"welcome-text\",
    \"timestamp\": \"$TIMESTAMP\",
    \"context\": {
      \"action\": \"greet\"
    }
  }" | jq .
echo ""

# 8. Delete Surface
echo "8️⃣  Deleting surface: $SURFACE_ID"
curl -s -X DELETE "$BASE_URL/a2ui/surfaces/$SURFACE_ID?sessionId=$SESSION_ID" | jq .
echo ""

echo "✅ A2UI API tests completed!"

