/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'a2uiSurface': MotiaStream<unknown>
    'a2uiMessage': MotiaStream<unknown>
  }

  interface Handlers {
    'RestaurantAgent': ApiRouteHandler<unknown, ApiResponse<200, unknown> | ApiResponse<500, unknown>, never>
    'HandleUserAction': ApiRouteHandler<unknown, ApiResponse<200, unknown> | ApiResponse<400, unknown>, { topic: 'a2ui.action.received'; data: unknown }>
    'UpdateDataModel': ApiRouteHandler<unknown, ApiResponse<200, unknown> | ApiResponse<404, unknown>, never>
    'UpdateComponents': ApiRouteHandler<unknown, ApiResponse<200, unknown> | ApiResponse<400, unknown> | ApiResponse<404, unknown>, never>
    'ProcessUserAction': EventHandler<unknown, { topic: 'a2ui.llm.request'; data: unknown }>
    'ListSurfaces': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown>, never>
    'GetSurface': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<404, unknown>, never>
    'GenerateUI': EventHandler<unknown, { topic: 'a2ui.components.generated'; data: unknown }>
    'DeleteSurface': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<404, unknown>, never>
    'CreateSurface': ApiRouteHandler<unknown, ApiResponse<201, unknown> | ApiResponse<400, unknown> | ApiResponse<409, unknown>, never>
    'ApplyGeneratedUI': EventHandler<unknown, never>
    'GeminiUIGenerator': ApiRouteHandler<unknown, ApiResponse<200, unknown> | ApiResponse<400, unknown> | ApiResponse<500, unknown>, never>
  }
    
}